// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using ElContadorPampero.Models;
using Microsoft.EntityFrameworkCore;

namespace ElContadorPampero.Data;

public partial class ElContador2025V2Context : DbContext
{
    public ElContador2025V2Context()
    {
    }

    public ElContador2025V2Context(DbContextOptions<ElContador2025V2Context> options)
        : base(options)
    {
    }

    public virtual DbSet<AsientoContable> AsientoContables { get; set; }

    public virtual DbSet<BalanceGeneral> BalanceGenerals { get; set; }

    public virtual DbSet<Contabilidad> Contabilidads { get; set; }

    public virtual DbSet<CuentaContable> CuentaContables { get; set; }

    public virtual DbSet<DetalleAsientoContable> DetalleAsientoContables { get; set; }

    public virtual DbSet<Mayoreo> Mayoreos { get; set; }

//    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
//        => optionsBuilder.UseSqlServer("Data Source=HEMM2024GAMING\\SQLEXPRESS;Initial Catalog=ElContador2025V2;Integrated Security=True;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AsientoContable>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_AsientoContable_1");

            entity.HasOne(d => d.Contabilidad).WithMany(p => p.AsientoContables)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AsientoContable_Contabilidad");
        });

        modelBuilder.Entity<BalanceGeneral>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<Contabilidad>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Contabil__3214EC07A4F05597");
        });

        modelBuilder.Entity<DetalleAsientoContable>(entity =>
        {
            entity.HasOne(d => d.AsientoContable).WithMany(p => p.DetalleAsientoContables)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DetalleAsientoContable_AsientoContable");

            entity.HasOne(d => d.CuentaContable).WithMany(p => p.DetalleAsientoContables)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DetalleAsientoContable_CuentaContable");
        });

        modelBuilder.Entity<Mayoreo>(entity =>
        {
            entity.HasOne(d => d.CuentaContable).WithMany(p => p.Mayoreos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Mayoreo_CuentaContable");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}