// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ElContadorPampero.Models;

[Table("Contabilidad")]
public partial class Contabilidad
{
    [Key]
    public int Id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime FechaCreacion { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Nombre { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime FechaInicioPeriodo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime FechaFinalPeriodo { get; set; }

    [Required]
    [StringLength(25)]
    [Unicode(false)]
    public string Empresa { get; set; }

    [InverseProperty("Contabilidad")]
    public virtual ICollection<AsientoContable> AsientoContables { get; set; } = new List<AsientoContable>();
}