// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ElContadorPampero.Models;

[Table("Mayoreo")]
public partial class Mayoreo
{
    [Key]
    public int Id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime PeriodoInicio { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime PeriodoFinal { get; set; }

    public int CuentaContableId { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal? TotalDebe { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal? TotalHaber { get; set; }

    [ForeignKey("CuentaContableId")]
    [InverseProperty("Mayoreos")]
    public virtual CuentaContable CuentaContable { get; set; }
}