// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ElContadorPampero.Models;

[Table("Usuario")]
public partial class Usuario
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(25)]
    [Unicode(false)]
    public string Identificacion { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Apellidos { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Nombre { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Pass { get; set; }

    [InverseProperty("Usuario")]
    public virtual ICollection<AsientoContable> AsientoContables { get; set; } = new List<AsientoContable>();

    [InverseProperty("Usuario")]
    public virtual ICollection<Contabilidad> Contabilidads { get; set; } = new List<Contabilidad>();
}